[server]
headless = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#f7931a"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1d24"
textColor = "#fafafa"

